<a href="https://colab.research.google.com/github/AbrahamKong/CMPE256-ML_Based_Spam_Filter_Assignment/blob/main/CMPE_256_ML_Based_Spam_Filter_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# Import neccassary library

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

ModuleNotFoundError: ignored

In [7]:
# Read In text from files

data_dir = "/content/"
data_files = [
    "Spam Dictionary.txt", 
    "Document1.txt", "Document2.txt", "Document3.txt",
    "Document4.txt", "Document5-1.txt", "Document6.txt"
]

data = pd.Series()
for file in data_files:
    f = open(data_dir + file, 'r')
    file_contents = f.read()
    data[file[:-4]] = file_contents
    f.close()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  # Remove the CWD from sys.path while we load stuff.


In [8]:
data.head

<bound method NDFrame.head of Spam Dictionary    Free \nClick here\nvisit\nopen attachment\ncal...
Document1          Free-Coupons for next movie. The above links w...
Document2          Free-Coupons for next movie. The above links w...
Document3          Our records indicate your Pension is under per...
Document4          Enter to win $25,000 and get a Free Hotel Nigh...
Document5-1        Dear recipient, \nAvangar Technologies announc...
Document6          I know that's an incredible statement, but bea...
dtype: object>

In [ ]:
# Count Word for each document

from collections import Counter

bag_of_words = (
    data.
    str.lower().                  # convert all letters to lowercase
    str.replace("[^\w\s]", " ").  # replace non-alphanumeric characters by whitespace
    str.split()                   # split on whitespace
).apply(Counter)

bag_of_words

**TF-iDF**

In [ ]:
# Set up TD

tf = pd.DataFrame(list(bag_of_words))
tf

free  click  here  visit  open  ...   ve  helped  4000   do  same
0   1.0    1.0   1.0    1.0   1.0  ...  NaN     NaN   NaN  NaN   NaN
1   1.0    NaN   NaN    1.0   NaN  ...  NaN     NaN   NaN  NaN   NaN
2   1.0    NaN   NaN    1.0   NaN  ...  NaN     NaN   NaN  NaN   NaN
3   1.0    NaN   NaN    NaN   NaN  ...  NaN     NaN   NaN  NaN   NaN
4   2.0    1.0   1.0    NaN   NaN  ...  NaN     NaN   NaN  NaN   NaN
5   NaN    NaN   NaN    NaN   NaN  ...  NaN     NaN   NaN  NaN   NaN
6   NaN    NaN   NaN    NaN   NaN  ...  1.0     1.0   1.0  1.0   1.0

[7 rows x 253 columns]

In [ ]:
# Fill N/A value with 0

tf = tf.fillna(0)
tf

free  click  here  visit  open  ...   ve  helped  4000   do  same
0   1.0    1.0   1.0    1.0   1.0  ...  0.0     0.0   0.0  0.0   0.0
1   1.0    0.0   0.0    1.0   0.0  ...  0.0     0.0   0.0  0.0   0.0
2   1.0    0.0   0.0    1.0   0.0  ...  0.0     0.0   0.0  0.0   0.0
3   1.0    0.0   0.0    0.0   0.0  ...  0.0     0.0   0.0  0.0   0.0
4   2.0    1.0   1.0    0.0   0.0  ...  0.0     0.0   0.0  0.0   0.0
5   0.0    0.0   0.0    0.0   0.0  ...  0.0     0.0   0.0  0.0   0.0
6   0.0    0.0   0.0    0.0   0.0  ...  1.0     1.0   1.0  1.0   1.0

[7 rows x 253 columns]

In [ ]:
# Get document frequencies 

df = (tf > 0).sum(axis=0)
df

free      5
click     2
here      2
visit     3
open      1
         ..
ve        1
helped    1
4000      1
do        1
same      1
Length: 253, dtype: int64

In [ ]:
# Get IDFs


idf = np.log(len(tf) / df)
idf

free      0.336472
click     1.252763
here      1.252763
visit     0.847298
open      1.945910
            ...   
ve        1.945910
helped    1.945910
4000      1.945910
do        1.945910
same      1.945910
Length: 253, dtype: float64

In [ ]:
# Calculate TF-IDFs


tf_idf = tf * idf
tf_idf

free     click      here     visit  ...   helped     4000       do     same
0  0.336472  1.252763  1.252763  0.847298  ...  0.00000  0.00000  0.00000  0.00000
1  0.336472  0.000000  0.000000  0.847298  ...  0.00000  0.00000  0.00000  0.00000
2  0.336472  0.000000  0.000000  0.847298  ...  0.00000  0.00000  0.00000  0.00000
3  0.336472  0.000000  0.000000  0.000000  ...  0.00000  0.00000  0.00000  0.00000
4  0.672944  1.252763  1.252763  0.000000  ...  0.00000  0.00000  0.00000  0.00000
5  0.000000  0.000000  0.000000  0.000000  ...  0.00000  0.00000  0.00000  0.00000
6  0.000000  0.000000  0.000000  0.000000  ...  1.94591  1.94591  1.94591  1.94591

[7 rows x 253 columns]

**Cisine Similarity**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer(norm=None) # Do not normalize.
vec.fit(data) # This determines the vocabulary.
tf_idf_sparse = vec.transform(data)

In [ ]:
# Calculate the numerator.
a = tf_idf_sparse[0, :]
b = tf_idf_sparse[2, :]
dot = a.multiply(b).sum()

# Calculate the terms in the denominator.
a_len = np.sqrt(a.multiply(a).sum())
b_len = np.sqrt(b.multiply(b).sum())

# Cosine similarity is their ratio.
dot / (a_len * b_len)

0.0726125632224235

In [ ]:
# Calculate the numerators.
a = tf_idf_sparse[0, :]
B = tf_idf_sparse
dot = a.multiply(B).sum(axis=1)
dot

matrix([[85.1008064 ],
        [ 7.39161987],
        [ 7.39161987],
        [21.27654777],
        [11.1636193 ],
        [19.61842265],
        [11.77105359]])

In [ ]:
# Calculate the denominators.
a_len = np.sqrt(a.multiply(a).sum())
b_len = np.sqrt(B.multiply(B).sum(axis=1))
print(a_len)
b_len

9.225009831737749


matrix([[ 9.22500983],
        [11.03471241],
        [11.03471241],
        [11.87504791],
        [21.94143017],
        [28.5998429 ],
        [29.62872436]])

In [ ]:
# Calculate their ratio to obtain cosine similarities.
dot / (a_len * b_len)

matrix([[1.        ],
        [0.07261256],
        [0.07261256],
        [0.19422224],
        [0.05515352],
        [0.07435901],
        [0.0430661 ]])

In [ ]:
cos_similarities = pd.DataFrame(dot / (a_len * b_len))[0]
most_similar = cos_similarities.sort_values(ascending=False)
most_similar

0    1.000000
3    0.194222
5    0.074359
2    0.072613
1    0.072613
4    0.055154
6    0.043066
Name: 0, dtype: float64