<a href="https://colab.research.google.com/github/AbrahamKong/CMPE256-ML_Based_Spam_Filter_Assignment/blob/main/CMPE_256_ML_Based_Spam_Filter_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [263]:
# Import neccassary library

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [264]:
# read in data

data = pd.read_csv('/content/data1.csv')

In [265]:
data.head()

Spam                                      Email Content
0     1  Free-Coupons for next movie. The above links w...
1     1  Free-Coupons for next movie. The above links w...
2     1  Our records indicate your Pension is under per...
3     1  Enter to win $25,000 and get a Free Hotel Nigh...
4     1  Dear recipient, \nAvangar Technologies announc...

In [266]:
len(data)

6

In [267]:
# num of spam in the data set

len(data['Spam']=='1')

6

In [268]:
data_x = data['Email Content']
data_y = data['Spam']

In [269]:
# set up Tf-iDf Tokenizer

tv = TfidfVectorizer(min_df=1, stop_words='english')

In [270]:
# split to prep the data

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2, random_state=4)
x_train.head

<bound method NDFrame.head of 3    Enter to win $25,000 and get a Free Hotel Nigh...
0    Free-Coupons for next movie. The above links w...
1    Free-Coupons for next movie. The above links w...
2    Our records indicate your Pension is under per...
Name: Email Content, dtype: object>

In [271]:
# train from given Spam Dictionary document

x_traintv = tv.fit_transform(["Free", "Click here", "visit", "open attachment", "call this number", "money", "Out", "extra", "offer", "available", "Pension", "Opportunity", "Chance", "Investment", "Pension"])

In [272]:
# Show the Tf-iDf

x_traintv.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        ],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0. 

In [273]:
tv.get_feature_names()

['attachment',
 'available',
 'chance',
 'click',
 'extra',
 'free',
 'investment',
 'money',
 'number',
 'offer',
 'open',
 'opportunity',
 'pension',
 'visit']

In [274]:
tv1 = TfidfVectorizer(min_df=1, stop_words='english')

In [275]:
x_traintv = tv1.fit_transform(x_train)

In [276]:
a = x_traintv.toarray()

In [277]:
a

array([[0.36618526, 0.12206175, 0.12206175, 0.09623489, 0.        ,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.12206175, 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.12206175, 0.12739377, 0.12206175,
        0.12206175, 0.        , 0.        , 0.        , 0.12206175,
        0.12206175, 0.        , 0.        , 0.12206175, 0.12206175,
        0.        , 0.12206175, 0.12206175, 0.        , 0.12206175,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.        ,
        0.        , 0.        , 0.        , 0.2441235 , 0.12206175,
        0.12206175, 0.        , 0.        , 0.        , 0.        ,
        0.12206175, 0.12206175, 0.07791044, 0.12206175, 0.12206175,
        0.        , 0.        , 0.12206175, 0.12206175, 0.        ,
        0.        , 0.36618526, 0.        , 0.12

In [278]:
tv1.inverse_transform(a[0])

[array(['000', '10', '100', '25', 'animals', 'articles', 'barnyard', 'bmw',
        'book', 'business', 'cats', 'chances', 'chocolate', 'choice',
        'click', 'company', 'computer', 'convertible', 'cool', 'crazy',
        'discount', 'enter', 'ezventure', 'fast', 'free', 'funny', 'gives',
        'home', 'hotel', 'internet', 'just', 'membership', 'microsoft',
        'nail', 'netmarket', 'night', 'office', 'plus', 'polish', 'prize',
        'shares', 'shopping', 'site', 'spremier', 'stock', 'trial',
        'trivia', 'win', 'z3'], dtype='<U11')]

In [279]:
x_train.iloc[0]

"Enter to win $25,000 and get a Free Hotel Night! Just click here for a $1 trial membership in NetMarket, the Internet'spremier discount shopping site: \n  \n \nFast Company EZVenture gives you FREE business articles, PLUS, you could win YOUR CHOICE of a BMW Z3 convertible, $100,000, shares of Microsoft stock, or a home office computer. Go there and get your chances to win now. \nA crazy-funny-cool trivia book with a $10,000 prize? PLUS chocolate, nail polish, cats, barnyard animals, and more? "

In [280]:
x_testtv = tv1.transform(x_test)

In [281]:
x_testtv.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.56599407, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.56599407, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.28299704, 0.        , 0.28299704,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.44623623, 0.  

In [282]:
# Set up ML method using MultinomialNB
mnb = MultinomialNB()

In [283]:
# Set data as integer to fit the method needs

y_train = y_train.astype('int')
y_train

3    1
0    1
1    1
2    1
Name: Spam, dtype: int64

In [284]:
# Train the data

mnb.fit(x_traintv, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [285]:
# Make predictions

predictions=mnb.predict(x_testcv)
predictions

array([1, 1])

In [286]:
actual = np.array(y_test)
actual

array([1, 1])

In [287]:
count=0

In [290]:
for i in range (len(predictions)):
    if predictions[i]==actual[i]:
        count=count+1

In [291]:
count

2

In [292]:
len(predictions)

2

In [293]:
# Prediction Accuracy Rate
# since all the document are spam, it should return 1

count / len(predictions)

1.0