<a href="https://colab.research.google.com/github/AbrahamKong/CMPE256-ML_Based_Spam_Filter_Assignment/blob/main/CMPE_256_ML_Based_Spam_Filter_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
# Import neccassary library

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [87]:


df = pd.read_csv('/content/data1.csv')

In [88]:
df.head()

Email Content  Spam
0  Free-Coupons for next movie. The above links w...     0
1  Free-Coupons for next movie. The above links w...     0
2  Our records indicate your Pension is under per...     0
3  Enter to win $25,000 and get a Free Hotel Nigh...     0
4  Dear recipient, \nAvangar Technologies announc...     0

In [89]:
len(df)

6

In [90]:
df_x = df['Email Content']
df_y = df['Spam']

In [91]:
cv = TfidfVectorizer(min_df=1, stop_words='english')

In [92]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [93]:
x_traincv = cv.fit_transform(["Free", "Click here", "visit", "open attachment", "call this number", "money", "Out", "extra", "offer", "available", "Pension", "Opportunity", "Chance", "Investment", "Pension"])

In [94]:
# Show the Tf-iDf

x_traincv.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        ],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0. 

In [95]:
cv.get_feature_names()

['attachment',
 'available',
 'chance',
 'click',
 'extra',
 'free',
 'investment',
 'money',
 'number',
 'offer',
 'open',
 'opportunity',
 'pension',
 'visit']

In [105]:
tv1 = TfidfVectorizer(min_df=1, stop_words='english')

In [106]:
x_traincv = tv1.fit_transform(x_train)

In [107]:
a = x_traincv.toarray()

In [108]:
a

array([[0.36618526, 0.12206175, 0.12206175, 0.09623489, 0.        ,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.12206175, 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
        0.12206175, 0.12206175, 0.12206175, 0.12739377, 0.12206175,
        0.12206175, 0.        , 0.        , 0.        , 0.12206175,
        0.12206175, 0.        , 0.        , 0.12206175, 0.12206175,
        0.        , 0.12206175, 0.12206175, 0.        , 0.12206175,
        0.12206175, 0.12206175, 0.        , 0.12206175, 0.        ,
        0.        , 0.        , 0.        , 0.2441235 , 0.12206175,
        0.12206175, 0.        , 0.        , 0.        , 0.        ,
        0.12206175, 0.12206175, 0.07791044, 0.12206175, 0.12206175,
        0.        , 0.        , 0.12206175, 0.12206175, 0.        ,
        0.        , 0.36618526, 0.        , 0.12

In [109]:
a[0]

array([0.36618526, 0.12206175, 0.12206175, 0.09623489, 0.        ,
       0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
       0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
       0.12206175, 0.12206175, 0.12206175, 0.12206175, 0.12206175,
       0.12206175, 0.12206175, 0.        , 0.12206175, 0.12206175,
       0.12206175, 0.12206175, 0.12206175, 0.12739377, 0.12206175,
       0.12206175, 0.        , 0.        , 0.        , 0.12206175,
       0.12206175, 0.        , 0.        , 0.12206175, 0.12206175,
       0.        , 0.12206175, 0.12206175, 0.        , 0.12206175,
       0.12206175, 0.12206175, 0.        , 0.12206175, 0.        ,
       0.        , 0.        , 0.        , 0.2441235 , 0.12206175,
       0.12206175, 0.        , 0.        , 0.        , 0.        ,
       0.12206175, 0.12206175, 0.07791044, 0.12206175, 0.12206175,
       0.        , 0.        , 0.12206175, 0.12206175, 0.        ,
       0.        , 0.36618526, 0.        , 0.12206175])

In [110]:
tv1.inverse_transform(a[0])

[array(['000', '10', '100', '25', 'animals', 'articles', 'barnyard', 'bmw',
        'book', 'business', 'cats', 'chances', 'chocolate', 'choice',
        'click', 'company', 'computer', 'convertible', 'cool', 'crazy',
        'discount', 'enter', 'ezventure', 'fast', 'free', 'funny', 'gives',
        'home', 'hotel', 'internet', 'just', 'membership', 'microsoft',
        'nail', 'netmarket', 'night', 'office', 'plus', 'polish', 'prize',
        'shares', 'shopping', 'site', 'spremier', 'stock', 'trial',
        'trivia', 'win', 'z3'], dtype='<U11')]

In [112]:
x_train.iloc[0]

"Enter to win $25,000 and get a Free Hotel Night! Just click here for a $1 trial membership in NetMarket, the Internet'spremier discount shopping site: \n  \n \nFast Company EZVenture gives you FREE business articles, PLUS, you could win YOUR CHOICE of a BMW Z3 convertible, $100,000, shares of Microsoft stock, or a home office computer. Go there and get your chances to win now. \nA crazy-funny-cool trivia book with a $10,000 prize? PLUS chocolate, nail polish, cats, barnyard animals, and more? "

In [115]:
# Set up ML method using MultinomialNB
mnb = MultinomialNB()

In [116]:
# Set data as integer to fit the method needs

y_train = y_train.astype('int')

In [118]:
# Train the data

mnb.fit(x_traincv, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [119]:
# Extract Tf-iDf feature to data

x_testcv = cv1.transform(x_train)